Make sure that no missing modules are used
I grepped for import statements and tested them all. Here are the
ones that failed:

    from ulmic.external.localpotential import LocalPotential1D
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
        File "/home/vlad/Datashare/codes/solids/ulmic_github/ulmic/external/localpotential.py", line 9, in <module>
            import clog
    	ModuleNotFoundError: No module named 'clog'

    from ulmic.medium.dielectric_function import DielectricResponse
    >>> from ulmic.medium.dielectric_function import DielectricResponse
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      ModuleNotFoundError: No module named 'ulmic.medium.dielectric_function'

    from ulmic.medium.extrapolation import Extrapolation
    >>> from ulmic.medium.extrapolation import Extrapolation
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      ModuleNotFoundError: No module named 'ulmic.medium.extrapolation'

    from ulmic.medium.sum_rules import MediumConvergence
    >>> from ulmic.medium.sum_rules import MediumConvergence
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      ModuleNotFoundError: No module named 'ulmic.medium.sum_rules'

    import ulmic.tests.general
    >>> import ulmic.tests.general
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      ModuleNotFoundError: No module named 'ulmic.tests.general'

After that, I've commented out those lines that used the missing modules.